"use client";

import { useCallback, useEffect, useState } from "react";

/**
 * Generic CRUD hook for an editable list of `{ id: string, ... }` entries.
 *
 * Originally extracted from `PropertyCatalogEditor` after the Phase-13
 * performance pass. Centralizes three concerns that every catalog
 * editor in the app shares:
 *
 *   1. **Reference-equality dirty tracking** — `entries !== initial`
 *      gives an O(1) dirty signal. Replaces the old O(N)
 *      `JSON.stringify(entries) !== JSON.stringify(initial)` check that
 *      collapsed under thousands of rows. Any `setEntries` produces a
 *      new array reference, so dirty flips true on any edit; resetting
 *      to the original reference flips it back. False positives ("user
 *      added a row then deleted it") are acceptable because the worst
 *      case is just an enabled Save button on a no-op change.
 *
 *   2. **Stable per-row callbacks** — `updateEntry` and `removeEntry`
 *      are returned as `useCallback`-stable references so a memoized
 *      `EntryRow` component can skip re-render when its underlying
 *      entry hasn't changed.
 *
 *   3. **Reset on identity change** — `initialKey` is an opaque value
 *      (typically the catalog id or "draft") that, when it changes,
 *      re-seeds entries from `initialEntries`.
 *
 * The hook does NOT enforce min/max row counts (callers gate Save on
 * that themselves), but `addEntry` and `removeEntry` honor an optional
 * `min` / `max` cap and short-circuit when the cap is reached so the
 * underlying state stays consistent.
 */
export interface UseCatalogEntriesOptions<TEntry> {
  /** Lower bound — `removeEntry` becomes a no-op below this count. */
  min?: number;
  /** Upper bound — `addEntry` becomes a no-op above this count. */
  max?: number;
  /** Factory for a fresh blank entry (id is generated by the caller's
   * factory; the hook just appends what you return). */
  makeBlank: () => TEntry;
}

export interface UseCatalogEntriesResult<TEntry> {
  entries: TEntry[];
  /** Direct setter — escape hatch for batch operations / discard. */
  setEntries: (next: TEntry[]) => void;
  /**
   * Append a new blank entry at the end of the list. Returns the new
   * entry's id so the caller can scroll/focus it. Returns `null` if
   * the `max` cap blocked the add.
   */
  addEntry: () => string | null;
  /** Patch a single entry by id. */
  updateEntry: (id: string, patch: Partial<TEntry>) => void;
  /** Remove an entry by id (no-op when at `min`). */
  removeEntry: (id: string) => void;
  /** Reset to the initial reference. Useful for Discard. */
  reset: () => void;
  /** Reference-equality dirty check vs. the initial entries reference. */
  dirty: boolean;
}

/**
 * @param initialEntries the seed array — its REFERENCE identity is what
 *   the dirty check compares against. Pass the same reference back via
 *   `setEntries` to mark clean.
 * @param initialKey opaque identity that triggers a re-seed when changed
 *   (catalog switch / discard).
 * @param options hooks for blank-row factory + optional row caps.
 */
export function useCatalogEntries<TEntry extends { id: string }>(
  initialEntries: TEntry[],
  initialKey: string,
  options: UseCatalogEntriesOptions<TEntry>,
): UseCatalogEntriesResult<TEntry> {
  const [entries, setEntries] = useState<TEntry[]>(initialEntries);

  // Re-seed on identity change.
  useEffect(() => {
    setEntries(initialEntries);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialKey]);

  const updateEntry = useCallback(
    (id: string, patch: Partial<TEntry>) => {
      setEntries((curr) =>
        curr.map((e) => (e.id === id ? { ...e, ...patch } : e)),
      );
    },
    [],
  );

  const addEntry = useCallback((): string | null => {
    const blank = options.makeBlank();
    let added = false;
    setEntries((curr) => {
      if (options.max != null && curr.length >= options.max) return curr;
      added = true;
      return [...curr, blank];
    });
    return added ? blank.id : null;
    // makeBlank intentionally not in deps — callers pass a stable factory
    // (e.g. `() => ({ id: newEntryId(), ... })`) but we don't want to
    // re-create addEntry per render even if they don't.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [options.max]);

  const removeEntry = useCallback(
    (id: string) => {
      setEntries((curr) => {
        if (options.min != null && curr.length <= options.min) return curr;
        return curr.filter((e) => e.id !== id);
      });
    },
    [options.min],
  );

  const reset = useCallback(() => {
    setEntries(initialEntries);
  }, [initialEntries]);

  // Reference-equality dirty check. O(1) — the headline win over
  // JSON.stringify-based comparison.
  const dirty = entries !== initialEntries;

  return {
    entries,
    setEntries,
    addEntry,
    updateEntry,
    removeEntry,
    reset,
    dirty,
  };
}
