"""create initial tables

Revision ID: 70fa3fca9b73
Revises: 
Create Date: 2026-04-19 21:15:01.621448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '70fa3fca9b73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('failed_documents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_patterns',
    sa.Column('vendor_name_normalized', sa.String(length=512), nullable=False),
    sa.Column('vendor_name_display', sa.String(length=512), nullable=False),
    sa.Column('field_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name_normalized', name='uq_vendor_pattern_name')
    )
    op.create_index(op.f('ix_vendor_patterns_vendor_name_normalized'), 'vendor_patterns', ['vendor_name_normalized'], unique=False)
    op.create_table('documents',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('route_used', sa.String(length=32), nullable=False),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_batch_id'), 'documents', ['batch_id'], unique=False)
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_table('export_jobs',
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_batch_id'), 'export_jobs', ['batch_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('adapter_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('raw_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=False)
    op.create_table('invoices',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name', sa.String(length=512), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=64), nullable=True),
    sa.Column('bill_to_name', sa.String(length=512), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('property_code', sa.String(length=64), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('service_period_start', sa.Date(), nullable=True),
    sa.Column('service_period_end', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_type', sa.String(length=32), nullable=False),
    sa.Column('utility_type', sa.String(length=32), nullable=True),
    sa.Column('account_number', sa.String(length=128), nullable=True),
    sa.Column('meter_number', sa.String(length=128), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=True)
    op.create_index(op.f('ix_invoices_property_code'), 'invoices', ['property_code'], unique=False)
    op.create_index(op.f('ix_invoices_property_name'), 'invoices', ['property_name'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('gl_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('review_events',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('value_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_invoice_id'), 'review_events', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_review_events_reviewer_id'), 'review_events', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_events_reviewer_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_invoice_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_vendor_name'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_property_name'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_property_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_extraction_runs_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_export_jobs_batch_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_batch_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vendor_patterns_vendor_name_normalized'), table_name='vendor_patterns')
    op.drop_table('vendor_patterns')
    op.drop_table('batches')
    # ### end Alembic commands ###
